<?php

$categories = array(
    array('pk_i_id' => 1,   'i_position' => 1,  'fk_i_parent_id' => NULL, 's_name' => __('For sale')),
    array('pk_i_id' => 2,   'i_position' => 2,  'fk_i_parent_id' => NULL, 's_name' => __('Vehicles')),
    array('pk_i_id' => 3,   'i_position' => 3,  'fk_i_parent_id' => NULL, 's_name' => __('Classes')),
    array('pk_i_id' => 4,   'i_position' => 4,  'fk_i_parent_id' => NULL, 's_name' => __('Real estate')),
    array('pk_i_id' => 5,   'i_position' => 5,  'fk_i_parent_id' => NULL, 's_name' => __('Services')),
    array('pk_i_id' => 6,   'i_position' => 6,  'fk_i_parent_id' => NULL, 's_name' => __('Community')),
    array('pk_i_id' => 7,   'i_position' => 7,  'fk_i_parent_id' => NULL, 's_name' => __('Personals')),
    array('pk_i_id' => 8,   'i_position' => 8,  'fk_i_parent_id' => NULL, 's_name' => __('Jobs')),
    array('pk_i_id' => 9,   'i_position' => 1,  'fk_i_parent_id' => 1,    's_name' => __('Animals')),
    array('pk_i_id' => 10,  'i_position' => 2,  'fk_i_parent_id' => 1,    's_name' => __('Art - Collectibles')),
    array('pk_i_id' => 11,  'i_position' => 3,  'fk_i_parent_id' => 1,    's_name' => __('Barter')),
    array('pk_i_id' => 12,  'i_position' => 4,  'fk_i_parent_id' => 1,    's_name' => __('Books - Magazines')),
    array('pk_i_id' => 13,  'i_position' => 5,  'fk_i_parent_id' => 1,    's_name' => __('Cameras - Camera Accessories')),
    array('pk_i_id' => 14,  'i_position' => 6,  'fk_i_parent_id' => 1,    's_name' => __('CDs - Records')),
    array('pk_i_id' => 15,  'i_position' => 7,  'fk_i_parent_id' => 1,    's_name' => __('Cell Phones - Accessories')),
    array('pk_i_id' => 16,  'i_position' => 8,  'fk_i_parent_id' => 1,    's_name' => __('Clothing')),
    array('pk_i_id' => 17,  'i_position' => 9,  'fk_i_parent_id' => 1,    's_name' => __('Computers - Hardware')),
    array('pk_i_id' => 18,  'i_position' => 10, 'fk_i_parent_id' => 1,    's_name' => __('DVD')),
    array('pk_i_id' => 19,  'i_position' => 11, 'fk_i_parent_id' => 1,    's_name' => __('Electronics')),
    array('pk_i_id' => 20,  'i_position' => 12, 'fk_i_parent_id' => 1,    's_name' => __('For Babies - Infants')),
    array('pk_i_id' => 21,  'i_position' => 13, 'fk_i_parent_id' => 1,    's_name' => __('Garage Sale')),
    array('pk_i_id' => 22,  'i_position' => 14, 'fk_i_parent_id' => 1,    's_name' => __('Health - Beauty')),
    array('pk_i_id' => 23,  'i_position' => 15, 'fk_i_parent_id' => 1,    's_name' => __('Home - Furniture - Garden Supplies')),
    array('pk_i_id' => 24,  'i_position' => 16, 'fk_i_parent_id' => 1,    's_name' => __('Jewelry - Watches')),
    array('pk_i_id' => 25,  'i_position' => 17, 'fk_i_parent_id' => 1,    's_name' => __('Musical Instruments')),
    array('pk_i_id' => 26,  'i_position' => 18, 'fk_i_parent_id' => 1,    's_name' => __('Sporting Goods - Bicycles')),
    array('pk_i_id' => 27,  'i_position' => 19, 'fk_i_parent_id' => 1,    's_name' => __('Tickets')),
    array('pk_i_id' => 28,  'i_position' => 20, 'fk_i_parent_id' => 1,    's_name' => __('Toys - Games - Hobbies')),
    array('pk_i_id' => 29,  'i_position' => 21, 'fk_i_parent_id' => 1,    's_name' => __('Video Games - Consoles')),
    array('pk_i_id' => 30,  'i_position' => 22, 'fk_i_parent_id' => 1,    's_name' => __('Everything Else')),
    array('pk_i_id' => 31,  'i_position' => 1,  'fk_i_parent_id' => 2,    's_name' => __('Cars')),
    array('pk_i_id' => 32,  'i_position' => 2,  'fk_i_parent_id' => 2,    's_name' => __('Car Parts')),
    array('pk_i_id' => 33,  'i_position' => 3,  'fk_i_parent_id' => 2,    's_name' => __('Motorcycles')),
    array('pk_i_id' => 34,  'i_position' => 4,  'fk_i_parent_id' => 2,    's_name' => __('Boats - Ships')),
    array('pk_i_id' => 35,  'i_position' => 5,  'fk_i_parent_id' => 2,    's_name' => __('RVs - Campers - Caravans')),
    array('pk_i_id' => 36,  'i_position' => 6,  'fk_i_parent_id' => 2,    's_name' => __('Trucks - Commercial Vehicles')),
    array('pk_i_id' => 37,  'i_position' => 7,  'fk_i_parent_id' => 2,    's_name' => __('Other Vehicles')),
    array('pk_i_id' => 38,  'i_position' => 1,  'fk_i_parent_id' => 3,    's_name' => __('Computer - Multimedia Classes')),
    array('pk_i_id' => 39,  'i_position' => 2,  'fk_i_parent_id' => 3,    's_name' => __('Language Classes')),
    array('pk_i_id' => 40,  'i_position' => 3,  'fk_i_parent_id' => 3,    's_name' => __('Music - Theatre - Dance Classes')),
    array('pk_i_id' => 41,  'i_position' => 4,  'fk_i_parent_id' => 3,    's_name' => __('Tutoring - Private Lessons')),
    array('pk_i_id' => 42,  'i_position' => 5,  'fk_i_parent_id' => 3,    's_name' => __('Other Classes')),
    array('pk_i_id' => 43,  'i_position' => 1,  'fk_i_parent_id' => 4,    's_name' => __('Houses - Apartments for Sale')),
    array('pk_i_id' => 44,  'i_position' => 2,  'fk_i_parent_id' => 4,    's_name' => __('Houses - Apartments for Rent')),
    array('pk_i_id' => 45,  'i_position' => 3,  'fk_i_parent_id' => 4,    's_name' => __('Rooms for Rent - Shared')),
    array('pk_i_id' => 46,  'i_position' => 4,  'fk_i_parent_id' => 4,    's_name' => __('Housing Swap')),
    array('pk_i_id' => 47,  'i_position' => 5,  'fk_i_parent_id' => 4,    's_name' => __('Vacation Rentals')),
    array('pk_i_id' => 48,  'i_position' => 6,  'fk_i_parent_id' => 4,    's_name' => __('Parking Spots')),
    array('pk_i_id' => 49,  'i_position' => 7,  'fk_i_parent_id' => 4,    's_name' => __('Land')),
    array('pk_i_id' => 50,  'i_position' => 8,  'fk_i_parent_id' => 4,    's_name' => __('Office - Commercial Space')),
    array('pk_i_id' => 51,  'i_position' => 9,  'fk_i_parent_id' => 4,    's_name' => __('Shops for Rent - Sale')),
    array('pk_i_id' => 52,  'i_position' => 1,  'fk_i_parent_id' => 5,    's_name' => __('Babysitter - Nanny')),
    array('pk_i_id' => 53,  'i_position' => 2,  'fk_i_parent_id' => 5,    's_name' => __('Casting - Auditions')),
    array('pk_i_id' => 54,  'i_position' => 3,  'fk_i_parent_id' => 5,    's_name' => __('Computer')),
    array('pk_i_id' => 55,  'i_position' => 4,  'fk_i_parent_id' => 5,    's_name' => __('Event Services')),
    array('pk_i_id' => 56,  'i_position' => 5,  'fk_i_parent_id' => 5,    's_name' => __('Health - Beauty - Fitness')),
    array('pk_i_id' => 57,  'i_position' => 6,  'fk_i_parent_id' => 5,    's_name' => __('Horoscopes - Tarot')),
    array('pk_i_id' => 58,  'i_position' => 7,  'fk_i_parent_id' => 5,    's_name' => __('Household - Domestic Help')),
    array('pk_i_id' => 59,  'i_position' => 8,  'fk_i_parent_id' => 5,    's_name' => __('Moving - Storage')),
    array('pk_i_id' => 60,  'i_position' => 9,  'fk_i_parent_id' => 5,    's_name' => __('Repair')),
    array('pk_i_id' => 61,  'i_position' => 10, 'fk_i_parent_id' => 5,    's_name' => __('Writing - Editing - Translating')),
    array('pk_i_id' => 62,  'i_position' => 11, 'fk_i_parent_id' => 5,    's_name' => __('Other Services')),
    array('pk_i_id' => 63,  'i_position' => 1,  'fk_i_parent_id' => 6,    's_name' => __('Carpool')),
    array('pk_i_id' => 64,  'i_position' => 2,  'fk_i_parent_id' => 6,    's_name' => __('Community Activities')),
    array('pk_i_id' => 65,  'i_position' => 3,  'fk_i_parent_id' => 6,    's_name' => __('Events')),
    array('pk_i_id' => 66,  'i_position' => 4,  'fk_i_parent_id' => 6,    's_name' => __('Musicians - Artists - Bands')),
    array('pk_i_id' => 67,  'i_position' => 5,  'fk_i_parent_id' => 6,    's_name' => __('Volunteers')),
    array('pk_i_id' => 68,  'i_position' => 6,  'fk_i_parent_id' => 6,    's_name' => __('Lost And Found')),
    array('pk_i_id' => 69,  'i_position' => 1,  'fk_i_parent_id' => 7,    's_name' => __('Women looking for Men')),
    array('pk_i_id' => 70,  'i_position' => 2,  'fk_i_parent_id' => 7,    's_name' => __('Men looking for Women')),
    array('pk_i_id' => 71,  'i_position' => 3,  'fk_i_parent_id' => 7,    's_name' => __('Men looking for Men')),
    array('pk_i_id' => 72,  'i_position' => 4,  'fk_i_parent_id' => 7,    's_name' => __('Women looking for Women')),
    array('pk_i_id' => 73,  'i_position' => 5,  'fk_i_parent_id' => 7,    's_name' => __('Friendship - Activity Partners')),
    array('pk_i_id' => 74,  'i_position' => 6,  'fk_i_parent_id' => 7,    's_name' => __('Missed Connections')),
    array('pk_i_id' => 75,  'i_position' => 1,  'fk_i_parent_id' => 8,    's_name' => __('Accounting - Finance')),
    array('pk_i_id' => 76,  'i_position' => 2,  'fk_i_parent_id' => 8,    's_name' => __('Advertising - Public Relations')),
    array('pk_i_id' => 77,  'i_position' => 3,  'fk_i_parent_id' => 8,    's_name' => __('Arts - Entertainment - Publishing')),
    array('pk_i_id' => 78,  'i_position' => 4,  'fk_i_parent_id' => 8,    's_name' => __('Clerical - Administrative')),
    array('pk_i_id' => 79,  'i_position' => 5,  'fk_i_parent_id' => 8,    's_name' => __('Customer Service')),
    array('pk_i_id' => 80,  'i_position' => 6,  'fk_i_parent_id' => 8,    's_name' => __('Education - Training')),
    array('pk_i_id' => 81,  'i_position' => 7,  'fk_i_parent_id' => 8,    's_name' => __('Engineering - Architecture')),
    array('pk_i_id' => 82,  'i_position' => 8,  'fk_i_parent_id' => 8,    's_name' => __('Healthcare')),
    array('pk_i_id' => 83,  'i_position' => 9,  'fk_i_parent_id' => 8,    's_name' => __('Human Resource')),
    array('pk_i_id' => 84,  'i_position' => 10, 'fk_i_parent_id' => 8,    's_name' => __('Internet')),
    array('pk_i_id' => 85,  'i_position' => 11, 'fk_i_parent_id' => 8,    's_name' => __('Legal')),
    array('pk_i_id' => 86,  'i_position' => 12, 'fk_i_parent_id' => 8,    's_name' => __('Manual Labor')),
    array('pk_i_id' => 87,  'i_position' => 13, 'fk_i_parent_id' => 8,    's_name' => __('Manufacturing - Operations')),
    array('pk_i_id' => 88,  'i_position' => 14, 'fk_i_parent_id' => 8,    's_name' => __('Marketing')),
    array('pk_i_id' => 89,  'i_position' => 15, 'fk_i_parent_id' => 8,    's_name' => __('Non-profit - Volunteer')),
    array('pk_i_id' => 90,  'i_position' => 16, 'fk_i_parent_id' => 8,    's_name' => __('Real Estate')),
    array('pk_i_id' => 91,  'i_position' => 17, 'fk_i_parent_id' => 8,    's_name' => __('Restaurant - Food Service')),
    array('pk_i_id' => 92,  'i_position' => 18, 'fk_i_parent_id' => 8,    's_name' => __('Retail')),
    array('pk_i_id' => 93,  'i_position' => 19, 'fk_i_parent_id' => 8,    's_name' => __('Sales')),
    array('pk_i_id' => 94,  'i_position' => 20, 'fk_i_parent_id' => 8,    's_name' => __('Technology')),
    array('pk_i_id' => 95,  'i_position' => 21, 'fk_i_parent_id' => 8,    's_name' => __('Other Jobs'))
);


$item = array(
    'catId' => 9,
    'title' => __('Example Ad'),
    'description' => __('Description of the example ad. Insert here some usefull description of your ad.'),
    'contactName' => __('Example author'),
    'contactEmail' => __('osclass@example.com'),
    'country' => __('Example country'),
    'region' => __('Example region'),
    'city' => __('Example city'),
);


$page = array(
    's_title' => __('Example page title'),
    's_text' => __('This is an example page description. This is a good place to put your Terms of Service or any other help information.'),
    's_internal_name' => 'example_page'
);

// EOF: ./oc-includes/osclass/installer/basic_data.php