/* FYI: for now, only available on english */
/* MAIN CATEGORIES */
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id) VALUES (1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (1, 'en_US', 'For sale', 'for-sale');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id) VALUES (2);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (2, 'en_US', 'Vehicles', 'vehicles');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id) VALUES (3);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (3, 'en_US', 'Classes', 'classes');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id) VALUES (4);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (4, 'en_US', 'Real estate', 'real-estate');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id) VALUES (5);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (5, 'en_US', 'Services', 'services');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id) VALUES (6);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (6, 'en_US', 'Community', 'community');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id) VALUES (7);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (7, 'en_US', 'Personals','personals');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position) VALUES (8, '1');
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (8, 'en_US', 'Jobs', 'jobs');

/* SUBCATEGORIES */
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (9, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (9, 'en_US', 'Animals', 'animals');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (10, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (10, 'en_US', 'Art - Collectibles', 'art-collectibles');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (11, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (11, 'en_US', 'Barter', 'barter');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (12, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (12, 'en_US', 'Books - Magazines', 'books-magazines');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (13, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (13, 'en_US', 'Cameras - Camera Accessories', 'cameras-camera-accesories');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (14, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (14, 'en_US', 'CDs - Records', 'cds-records');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (15, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (15, 'en_US', 'Cell Phones - Accessories', 'cell-phones-accessories');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (16, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (16, 'en_US', 'Clothing', 'clothing');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (17, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (17, 'en_US', 'Computers - Hardware', 'computers-hardware');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (18, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (18, 'en_US', 'DVD', 'dvd');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (19, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (19, 'en_US', 'Electronics', 'electronics');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (20, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (20, 'en_US', 'For Babies - Infants', 'flor-babies-infants');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (21, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (21, 'en_US', 'Garage Sale', 'garage-sale');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (22, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (22, 'en_US', 'Health - Beauty', 'health-beauty');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (23, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (23, 'en_US', 'Home - Furniture - Garden Supplies', 'home-furniture-garden-supplies');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (24, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (24, 'en_US', 'Jewelry - Watches', 'jewelry-watches');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (25, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (25, 'en_US', 'Musical Instruments', 'musical-instruments');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (26, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (26, 'en_US', 'Sporting Goods - Bicycles', 'sporting-goods-bicycles');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (27, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (27, 'en_US', 'Tickets', 'tickets');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (28, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (28, 'en_US', 'Toys - Games - Hobbies', 'toys-games-hobbies');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (29, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (29, 'en_US', 'Video Games - Consoles', 'video-games-consoles');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (30, 1);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (30, 'en_US', 'Everything Else', 'everything-else');


INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (31, 2);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (31, 'en_US', 'Cars', 'cars');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (32, 2);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (32, 'en_US', 'Car Parts', 'car-parts');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (33, 2);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (33, 'en_US', 'Motorcycles', 'motorcycles');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (34, 2);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (34, 'en_US', 'Boats - Ships', 'boats-ships');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (35, 2);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (35, 'en_US', 'RVs - Campers - Caravans', 'rvs-campers-caravans');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (36, 2);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (36, 'en_US', 'Trucks - Commercial Vehicles', 'trucks-commercial-vehicles');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (37, 2);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (37, 'en_US', 'Other Vehicles', 'other-vehicles');

INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (38, 3);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (38, 'en_US', 'Computer - Multimedia Classes', 'computer-multimedia-classes');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (39, 3);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (39, 'en_US', 'Language Classes', 'language-classes');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (40, 3);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (40, 'en_US', 'Music - Theatre - Dance Classes', 'music-theatre-dance-classes');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (41, 3);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (41, 'en_US', 'Tutoring - Private Lessons', 'tutoring-private-lessons');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (42, 3);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (42, 'en_US', 'Other Classes', 'other-classes');

INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (43, 4);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (43, 'en_US', 'Houses - Apartments for Sale', 'houses-apartments-for-sale');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (44, 4);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (44, 'en_US', 'Houses - Apartments for Rent', 'houses-apartments-for-rent');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (45, 4);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (45, 'en_US', 'Rooms for Rent - Shared', 'rooms-for-rent-shared');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (46, 4);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (46, 'en_US', 'Housing Swap', 'housing-swap');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (47, 4);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (47, 'en_US', 'Vacation Rentals', 'vacation-rentals');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (48, 4);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (48, 'en_US', 'Parking Spots', 'parking-spots');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (49, 4);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (49, 'en_US', 'Land', 'land');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (50, 4);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (50, 'en_US', 'Office - Commercial Space', 'office-commercial-space');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (51, 4);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (51, 'en_US', 'Shops for Rent - Sale', 'shops-for-rent-sale');


INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (52, 5);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (52, 'en_US', 'Babysitter - Nanny', 'babysitter-nanny');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (53, 5);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (53, 'en_US', 'Casting - Auditions', 'casting-auditions');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (54, 5);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (54, 'en_US', 'Computer', 'computer');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (55, 5);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (55, 'en_US', 'Event Services', 'event-services');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (56, 5);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (56, 'en_US', 'Health - Beauty - Fitness', 'health-beauty-fitness');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (57, 5);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (57, 'en_US', 'Horoscopes - Tarot', 'horoscopes-tarot');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (58, 5);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (58, 'en_US', 'Household - Domestic Help', 'household-domestic-help');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (59, 5);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (59, 'en_US', 'Moving - Storage', 'moving-storage');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (60, 5);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (60, 'en_US', 'Repair', 'repair');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (61, 5);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (61, 'en_US', 'Writing - Editing - Translating', 'writing-editing-translating');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (62, 5);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (62, 'en_US', 'Other Services', 'other-services');

INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (63, 6);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (63, 'en_US', 'Carpool', 'carpool');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (64, 6);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (64, 'en_US', 'Community Activities', 'community-activities');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (65, 6);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (65, 'en_US', 'Events', 'events');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (66, 6);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (66, 'en_US', 'Musicians - Artists - Bands', 'musicians-artists-bands');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (67, 6);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (67, 'en_US', 'Volunteers', 'volunteers');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (68, 6);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (68, 'en_US', 'Lost And Found', 'lost-and-found');

INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (69, 7);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (69, 'en_US', 'Women looking for Men', 'women-looking-for-men');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (70, 7);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (70, 'en_US', 'Men looking for Women', 'men-looking-for-women');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (71, 7);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (71, 'en_US', 'Men looking for Men', 'men-looking-for-men');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (72, 7);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (72, 'en_US', 'Women looking for Women', 'women-looking-for-women');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (73, 7);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (73, 'en_US', 'Friendship - Activity Partners', 'friendship-activity-partners');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (74, 7);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (74, 'en_US', 'Missed Connections', 'missed-connections');

INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (75, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (75, 'en_US', 'Accounting Jobs - Finance Jobs', 'accounting-jobs-finance-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (76, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (76, 'en_US', 'Advertising Jobs - Public Relations Jobs', 'Advertising Jobs - Public Relations Jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (77, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (77, 'en_US', 'Arts Jobs - Entertainment Jobs - Publishing Jobs', 'arts-jobs-entertainment-jobs-publishing-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (78, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (78, 'en_US', 'Clerical Jobs - Administrative Jobs', 'clerical-jobs-administrative-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (79, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (79, 'en_US', 'Customer Service Jobs', 'customer-service-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (80, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (80, 'en_US', 'Education Jobs - Training Jobs', 'education-jobs-training-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (81, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (81, 'en_US', 'Engineering Jobs - Architecture Jobs', 'engineering-jobs-architecture-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (82, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (82, 'en_US', 'Healthcare Jobs', 'healthcare-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (83, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (83, 'en_US', 'Human Resource Jobs', 'human-resource-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (84, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (84, 'en_US', 'Internet Jobs', 'internet-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (85, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (85, 'en_US', 'Legal Jobs', 'legal-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (86, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (86, 'en_US', 'Manual Labor Jobs', 'manual-labor-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (87, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (87, 'en_US', 'Manufacturing Jobs - Operations Jobs', 'manufacturing-jobs-operation-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (88, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (88, 'en_US', 'Marketing Jobs', 'marketing-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (89, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (89, 'en_US', 'Non-profit Jobs - Volunteer Jobs', 'non-profit-jobs-volunteer-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (90, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (90, 'en_US', 'Real Estate Jobs', 'real-estate-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (91, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (91, 'en_US', 'Restaurant Jobs - Food Service Jobs', 'restaurant-jobs-food-service-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (92, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (92, 'en_US', 'Retail Jobs', 'retail-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (93, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (93, 'en_US', 'Sales Jobs', 'sales-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (94, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (94, 'en_US', 'Technology Jobs', 'technology-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, fk_i_parent_id) VALUES (95, 8);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (95, 'en_US', 'Other Jobs', 'other-jobs');
