/* FYI: for now, only available on english */
/* MAIN CATEGORIES */
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, b_enabled) VALUES (1, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (1, 'en_US', 'For sale', 'for-sale');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, b_enabled) VALUES (2, 2, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (2, 'en_US', 'Vehicles', 'vehicles');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, b_enabled) VALUES (3, 3, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (3, 'en_US', 'Classes', 'classes');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, b_enabled) VALUES (4, 4, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (4, 'en_US', 'Real estate', 'real-estate');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, b_enabled) VALUES (5, 5, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (5, 'en_US', 'Services', 'services');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, b_enabled) VALUES (6, 6, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (6, 'en_US', 'Community', 'community');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, b_enabled) VALUES (7, 7, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (7, 'en_US', 'Personals','personals');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, b_enabled) VALUES (8, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (8, 'en_US', 'Jobs', 'jobs');

/* SUBCATEGORIES */
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (9, 1, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (9, 'en_US', 'Animals', 'animals');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (10, 2, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (10, 'en_US', 'Art - Collectibles', 'art-collectibles');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (11, 3, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (11, 'en_US', 'Barter', 'barter');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (12, 4, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (12, 'en_US', 'Books - Magazines', 'books-magazines');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (13, 5, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (13, 'en_US', 'Cameras - Camera Accessories', 'cameras-camera-accesories');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (14, 6, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (14, 'en_US', 'CDs - Records', 'cds-records');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (15, 7, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (15, 'en_US', 'Cell Phones - Accessories', 'cell-phones-accessories');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (16, 8, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (16, 'en_US', 'Clothing', 'clothing');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (17, 9, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (17, 'en_US', 'Computers - Hardware', 'computers-hardware');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (18, 10, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (18, 'en_US', 'DVD', 'dvd');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (19, 11, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (19, 'en_US', 'Electronics', 'electronics');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (20, 12, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (20, 'en_US', 'For Babies - Infants', 'flor-babies-infants');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (21, 13, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (21, 'en_US', 'Garage Sale', 'garage-sale');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (22, 14, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (22, 'en_US', 'Health - Beauty', 'health-beauty');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (23, 15, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (23, 'en_US', 'Home - Furniture - Garden Supplies', 'home-furniture-garden-supplies');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (24, 16, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (24, 'en_US', 'Jewelry - Watches', 'jewelry-watches');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (25, 17, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (25, 'en_US', 'Musical Instruments', 'musical-instruments');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (26, 18, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (26, 'en_US', 'Sporting Goods - Bicycles', 'sporting-goods-bicycles');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (27, 19, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (27, 'en_US', 'Tickets', 'tickets');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (28, 20, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (28, 'en_US', 'Toys - Games - Hobbies', 'toys-games-hobbies');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (29, 21, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (29, 'en_US', 'Video Games - Consoles', 'video-games-consoles');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (30, 22, 1, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (30, 'en_US', 'Everything Else', 'everything-else');

INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (31, 1, 2, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (31, 'en_US', 'Cars', 'cars');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (32, 2, 2, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (32, 'en_US', 'Car Parts', 'car-parts');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (33, 3, 2, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (33, 'en_US', 'Motorcycles', 'motorcycles');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (34, 4, 2, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (34, 'en_US', 'Boats - Ships', 'boats-ships');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (35, 5, 2, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (35, 'en_US', 'RVs - Campers - Caravans', 'rvs-campers-caravans');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (36, 6, 2, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (36, 'en_US', 'Trucks - Commercial Vehicles', 'trucks-commercial-vehicles');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (37, 7, 2, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (37, 'en_US', 'Other Vehicles', 'other-vehicles');

INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (38, 1, 3, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (38, 'en_US', 'Computer - Multimedia Classes', 'computer-multimedia-classes');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (39, 2, 3, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (39, 'en_US', 'Language Classes', 'language-classes');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (40, 3, 3, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (40, 'en_US', 'Music - Theatre - Dance Classes', 'music-theatre-dance-classes');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (41, 4, 3, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (41, 'en_US', 'Tutoring - Private Lessons', 'tutoring-private-lessons');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (42, 5, 3, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (42, 'en_US', 'Other Classes', 'other-classes');

INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (43, 1, 4, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (43, 'en_US', 'Houses - Apartments for Sale', 'houses-apartments-for-sale');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (44, 2, 4, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (44, 'en_US', 'Houses - Apartments for Rent', 'houses-apartments-for-rent');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (45, 3, 4, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (45, 'en_US', 'Rooms for Rent - Shared', 'rooms-for-rent-shared');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (46, 4, 4, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (46, 'en_US', 'Housing Swap', 'housing-swap');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (47, 5, 4, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (47, 'en_US', 'Vacation Rentals', 'vacation-rentals');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (48, 6, 4, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (48, 'en_US', 'Parking Spots', 'parking-spots');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (49, 7, 4, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (49, 'en_US', 'Land', 'land');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (50, 8, 4, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (50, 'en_US', 'Office - Commercial Space', 'office-commercial-space');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (51, 9, 4, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (51, 'en_US', 'Shops for Rent - Sale', 'shops-for-rent-sale');

INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (52, 1, 5, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (52, 'en_US', 'Babysitter - Nanny', 'babysitter-nanny');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (53, 2, 5, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (53, 'en_US', 'Casting - Auditions', 'casting-auditions');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (54, 3, 5, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (54, 'en_US', 'Computer', 'computer');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (55, 4, 5, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (55, 'en_US', 'Event Services', 'event-services');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (56, 5, 5, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (56, 'en_US', 'Health - Beauty - Fitness', 'health-beauty-fitness');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (57, 6, 5, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (57, 'en_US', 'Horoscopes - Tarot', 'horoscopes-tarot');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (58, 7, 5, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (58, 'en_US', 'Household - Domestic Help', 'household-domestic-help');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (59, 8, 5, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (59, 'en_US', 'Moving - Storage', 'moving-storage');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (60, 9, 5, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (60, 'en_US', 'Repair', 'repair');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (61, 10, 5, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (61, 'en_US', 'Writing - Editing - Translating', 'writing-editing-translating');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (62, 11, 5, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (62, 'en_US', 'Other Services', 'other-services');

INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (63, 1, 6, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (63, 'en_US', 'Carpool', 'carpool');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (64, 2, 6, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (64, 'en_US', 'Community Activities', 'community-activities');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (65, 3, 6, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (65, 'en_US', 'Events', 'events');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (66, 4, 6, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (66, 'en_US', 'Musicians - Artists - Bands', 'musicians-artists-bands');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (67, 5, 6, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (67, 'en_US', 'Volunteers', 'volunteers');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (68, 6, 6, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (68, 'en_US', 'Lost And Found', 'lost-and-found');

INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (69, 1, 7, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (69, 'en_US', 'Women looking for Men', 'women-looking-for-men');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (70, 2, 7, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (70, 'en_US', 'Men looking for Women', 'men-looking-for-women');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (71, 3, 7, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (71, 'en_US', 'Men looking for Men', 'men-looking-for-men');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (72, 4, 7, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (72, 'en_US', 'Women looking for Women', 'women-looking-for-women');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (73, 5, 7, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (73, 'en_US', 'Friendship - Activity Partners', 'friendship-activity-partners');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (74, 6, 7, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (74, 'en_US', 'Missed Connections', 'missed-connections');

INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (75, 1, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (75, 'en_US', 'Accounting - Finance', 'accounting-finance');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (76, 2, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (76, 'en_US', 'Advertising - Public Relations', 'advertising-public-relations');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (77, 3, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (77, 'en_US', 'Arts - Entertainment - Publishing', 'arts-jobs-entertainment-jobs-publishing-jobs');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (78, 4, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (78, 'en_US', 'Clerical - Administrative', 'clerical-administrative');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (79, 5, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (79, 'en_US', 'Customer Service', 'customer-service');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (80, 6, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (80, 'en_US', 'Education - Training', 'education-training');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (81, 7, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (81, 'en_US', 'Engineering - Architecture', 'engineering-architecture');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (82, 8, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (82, 'en_US', 'Healthcare', 'healthcare');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (83, 9, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (83, 'en_US', 'Human Resource', 'human-resource');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (84, 10, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (84, 'en_US', 'Internet', 'internet');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (85, 11, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (85, 'en_US', 'Legal', 'legal');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (86, 12, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (86, 'en_US', 'Manual Labor', 'manual-labor');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (87, 13, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (87, 'en_US', 'Manufacturing - Operations', 'manufacturing-operation');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (88, 14, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (88, 'en_US', 'Marketing', 'marketing');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (89, 15, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (89, 'en_US', 'Non-profit - Volunteer', 'non-profit-volunteer');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (90, 16, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (90, 'en_US', 'Real Estate', 'real-estate');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (91, 17, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (91, 'en_US', 'Restaurant - Food Service', 'restaurant-food-service');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (92, 18, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (92, 'en_US', 'Retail', 'retail');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (93, 19, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (93, 'en_US', 'Sales', 'sales');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (94, 20, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (94, 'en_US', 'Technology', 'technology');
INSERT INTO /*TABLE_PREFIX*/t_category (pk_i_id, i_position, fk_i_parent_id, b_enabled) VALUES (95, 21, 8, 0);
INSERT INTO /*TABLE_PREFIX*/t_category_description (fk_i_category_id, fk_c_locale_code, s_name, s_slug) VALUES (95, 'en_US', 'Other Jobs', 'other-jobs');